/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as fantasySol from "./Fantasy.sol";
export type { fantasySol };
import type * as tokenSol from "./Token.sol";
export type { tokenSol };
export type { Oracle } from "./Oracle";
