/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as fantasySol from "./Fantasy.sol";
export * as tokenSol from "./Token.sol";
export { Oracle__factory } from "./Oracle__factory";
